export const themes = {
  dark: {
    navColor: "#1e2a3a",
    navText: "#b8bcc1",
    navTitle: "#fff",
    navIcon: "#eeede8",
    headerColor: "#111821",
    headerTitle: "#fff",
    headerText: "#b4b6b9",
    projectBody: "#111821",
    projectTitle: "#fff",
    cardColor: "#151e29",
    cardText: "#b4b6b9",
  },
  lightGrey: {
    navColor: "#8b8b8b",
    navText: "#eeede8",
    navTitle: "#eeede8",
    navIcon: "#eeede8",
    headerColor: "#efeee8",
    headerTitle: "#4c4b4c",
    headerText: "#4c4b4c",
    projectBody: "#fbfbfb",
    projectTitle: "#4c4b4c",
    cardColor: "#151e29",
  },
  lightOrange: {
    navColor: "#ffeddf",
    navText: "#42382e",
    navTitle: "#42382e",
    navIcon: "#42382e",
    headerColor: "#fff",
    headerTitle: "#42382e",
    headerText: "#42382e",
    projectTitle: "#42382e",
    projectBody: "#EBECF0",
  },
  wheatish: {
    navColor: "#f0ece3",
    navText: "#060607",
    navTitle: "#060607",
    navIcon: "#060607",
    headerColor: "#fff",
    headerTitle: "#42382e",
    headerText: "#42382e",
    projectTitle: "#42382e",
    projectBody: "#fff",
  },

  ligtWheat: {
    navColor: "#e0d7ce",
    navText: "#4c4c4c",
    navTitle: "#4c4c4c",
    navIcon: "#4c4c4c",
    headerColor: "#454641",
    headerTitle: "#fcfcfc",
    headerText: "#fcfcfc",
    projectTitle: "#fcfcfc",
    projectBody: "lightgrey",
  },

  darkGrey: {
    navColor: "#282828",
    navText: "#fbfdff",
    navTitle: "#fbfdff",
    navIcon: "#fbfdff",
    headerColor: "#cccccc",
    headerTitle: "#1f2b36",
    headerText: "#1f2b36",
    projectTitle: "#1f2b36",
    projectBody: "#fff",
  },
  whitish: {
    navColor: "#eaeae8",
    navTitle: "#ba9a61",
    navText: "#595957 ",
    navIcon: "#ba9a61",
    headerColor: "#2d3e50",
    headerTitle: "#ba9a61",
    headerText: "#fff",
    projectTitle: "#ba9a61",
    projectBody: "#fff",
  },
  glossyBlue: {
    navColor: "#283d58",
    navText: "#fff",
    navTitle: "#fff",
    navIcon: "#fff",
    headerColor: "#eaf1fb",
    headerTitle: "#4c4b4c",
    headerText: "#4c4b4c",
    projectBody: "#fbfbfb",
    projectTitle: "#4c4b4c",
    cardColor: "#151e29",
  },

  lightBrown: {
    navColor: "#767070",
    navText: "#fff",
    navTitle: "#fff",
    navIcon: "#fff",
    headerColor: "#f7f7f7",
    headerTitle: "#4c4b4c",
    headerText: "#4c4b4c",
    projectBody: "#fbfbfb",
    projectTitle: "#4c4b4c",
    cardColor: "#151e29",
  },
};
